### ISSUE TITLE
Add filter out option

### ISSUE THREAD

**Issue by Kubikx** [m-cat/cargo-deps#15]
there is `--filter every single dependency`

I would like to filter out common dependency like `libc`

It could be `--filter-out libc maybe other` and `libc` would not be on the graph.

I tried to use `cargo deps` to find out some dependencies, and encouter the problem that almost everything have an arrow to `libc`

**Comment by m-cat** [comment]
I hope #17 has addressed your need.

**Comment by Kubikx** [comment]
great thank you
