### ISSUE TITLE
Cycle dependencies support

### ISSUE THREAD

**Issue by frol** [m-cat/cargo-deps#19]
I wanted to use cargo-deps exactly to find all the cycles we have to illustrate how messed up our dependencies are... If you need a real-world project for tests, you can use: https://github.com/nearprotocol/nearcore/

**Comment by m-cat** [comment]
Cool, will take a look.

By the way, you might also want to take a look at [cargo-tree](https://github.com/sfackler/cargo-tree). That project is better in many ways -- cargo-dep is based on cargo-graph which has its own ad-hoc re-implementations of `cargo` functionality. I'll add cargo-tree to the README.

**Comment by frol** [comment]
cargo-tree works on our code base, but it does not present cycles nicely (at least I cannot see that)

**Comment by m-cat** [comment]
I haven't looked yet, but are you sure you have a cycle in your dependencies? I thought that was impossible lol

**Comment by frol** [comment]
We have those as `dev-dependencies` like: 

`neard -> near-client`, and `near-client -dev-dependency> neard`.

**Comment by m-cat** [comment]
There is a new project called [cargo-depgraph](https://sr.ht/~jplatte/cargo-depgraph/) which should support cycles.
