### ISSUE TITLE
`dbg` statements in released version

### ISSUE THREAD

**Issue by MarkMcCaskey** [m-cat/cargo-deps#7]
Hey, thanks for making this!  It's very nice to have something like this available

There are error messages that look like the output of the `dbg!` macro in the version I just installed from Cargo.

for example:
```
[/home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-deps-1.0.4/src/project.rs:28] root_crates = [
    RootCrate {
        name: "wasmer",
        ver: "0.5.0",
    },
]
```

**Comment by m-cat** [comment]
Thanks!
