### ISSUE TITLE
Feature Request: separate out dependency traversal library.

### ISSUE THREAD

**Issue by nathan-at-least** [m-cat/cargo-deps#9]
Hi, I'm exploring writing a utility that traverses a crate's dependencies transitively, and I came across this crate. This looks like a great tool, thanks!

What I would like is a library for the dependency graph computation/traversal that's used to generate the graphviz output. Could that be separated out so that `cargo-deps` can depend on it?

**Comment by m-cat** [comment]
Thanks for the suggestion, this is a great idea. I don't plan on doing any work on this crate at the moment as September will be quite busy for me. I'd be more than happy to review and merge any PRs -- otherwise I'll get around to this myself eventually.

**Comment by m-cat** [comment]
Closed by #11

**Comment by m-cat** [comment]
I guess this isn't useful for you until I publish a new version -- reopening for now.

**Comment by m-cat** [comment]
Version 1.2.0 released.
